//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  F:\Store\SANEK\Volume\NXOpen\5_ToolHolder\startDialog.cs
//
//        This file was generated by the NX Block UI Styler
//        Created by: Sanek
//              Version: NX 12
//              Date: 04-23-2020  (Format: mm-dd-yyyy)
//              Time: 00:24 (Format: hh-mm)
//
//==============================================================================


//------------------------------------------------------------------------------
//These imports are needed for the following template code
//------------------------------------------------------------------------------
using System;
using NXOpen;
using NXOpen.BlockStyler;

//------------------------------------------------------------------------------
//Represents Block Styler application class
//------------------------------------------------------------------------------
public class startDialog
{
    //class members
    private static Session theSession = null;
    private static UI theUI = null;
    private string theDlxFileName;
    private NXOpen.BlockStyler.BlockDialog theUserDefinedUIBlock;
    private NXOpen.BlockStyler.Group group0;// Block type: Group
    private NXOpen.BlockStyler.Button button01;// Block type: Button
    private NXOpen.BlockStyler.Button button0;// Block type: Button
    private NXOpen.BlockStyler.Button button02;// Block type: Button
    
    //------------------------------------------------------------------------------
    //Constructor for NX Styler class
    //------------------------------------------------------------------------------
    public startDialog()
    {
        try
        {
            theSession = Session.GetSession();
            theUI = UI.GetUI();
            theDlxFileName = "startDialog.dlx";
            theUserDefinedUIBlock = theUI.CreateDialog(theDlxFileName);
            theUserDefinedUIBlock.AddUpdateHandler(new NXOpen.BlockStyler.BlockDialog.Update(update_cb));
            theUserDefinedUIBlock.AddInitializeHandler(new NXOpen.BlockStyler.BlockDialog.Initialize(initialize_cb));
            theUserDefinedUIBlock.AddDialogShownHandler(new NXOpen.BlockStyler.BlockDialog.DialogShown(dialogShown_cb));
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            throw ex;
        }
    }
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Method Name: Dispose
    //------------------------------------------------------------------------------
    public void Dispose()
    {
        if(theUserDefinedUIBlock != null)
        {
            theUserDefinedUIBlock.Dispose();
            theUserDefinedUIBlock = null;
        }
    }
    
    //------------------------------------------------------------------------------
    //---------------------Block UI Styler Callback Functions--------------------------
    //------------------------------------------------------------------------------
    
    //------------------------------------------------------------------------------
    //Callback Name: initialize_cb
    //------------------------------------------------------------------------------
    public void initialize_cb()
    {
        try
        {
            group0 = (NXOpen.BlockStyler.Group)theUserDefinedUIBlock.TopBlock.FindBlock("group0");
            button01 = (NXOpen.BlockStyler.Button)theUserDefinedUIBlock.TopBlock.FindBlock("button01");
            button0 = (NXOpen.BlockStyler.Button)theUserDefinedUIBlock.TopBlock.FindBlock("button0");
            button02 = (NXOpen.BlockStyler.Button)theUserDefinedUIBlock.TopBlock.FindBlock("button02");
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: dialogShown_cb
    //This callback is executed just before the dialog launch. Thus any value set 
    //here will take precedence and dialog will be launched showing that value. 
    //------------------------------------------------------------------------------
    public void dialogShown_cb()
    {
        try
        {
            //---- Enter your callback code here -----
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
    }
    
    //------------------------------------------------------------------------------
    //Callback Name: update_cb
    //------------------------------------------------------------------------------
    public int update_cb( NXOpen.BlockStyler.UIBlock block)
    {
        try
        {
            if(block == button01)
            {
            //---------Enter your code here-----------
            }
            else if(block == button0)
            {
            //---------Enter your code here-----------
            }
            else if(block == button02)
            {
            //---------Enter your code here-----------
            }
        }
        catch (Exception ex)
        {
            //---- Enter your exception handling code here -----
            theUI.NXMessageBox.Show("Block Styler", NXMessageBox.DialogType.Error, ex.ToString());
        }
        return 0;
    }
    
    //------------------------------------------------------------------------------
    //Function Name: RegisterUserDefinedUIBlock
    //Registers itself to the dialog which contains this block
    //------------------------------------------------------------------------------
    public static startDialog RegisterUserDefinedUIBlock(NXOpen.BlockStyler.BlockDialog parentDialog, string blockID)
    {
        startDialog thestartDialog = new startDialog();
        parentDialog.RegisterUserDefinedUIBlock(thestartDialog.theUserDefinedUIBlock, blockID);
        return thestartDialog;
    }
    
    //------------------------------------------------------------------------------
    //Property Name: TopBlock
    //ReadOnly property to give access to TopBlock
    //------------------------------------------------------------------------------
    public NXOpen.BlockStyler.CompositeBlock TopBlock
    {
        get
        {
            if (theUserDefinedUIBlock != null)
            {
                return theUserDefinedUIBlock.TopBlock;
            }
            else
            {
                return null;
            }
        }
    }
    
}
